export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GF'
alias he='vi ~/shortcuts'
alias vrc='vi ~/.vimrc'
alias bp='vi ~/.bash_profile'
alias ec='vi ~/.editorconfig'
alias :q='exit'
